import localFont from 'next/font/local';
import Link from "next/link";
import '../assets/scss/global.scss';
import { ClutterProvider } from '../components/clutter/context';
import ClutterControl from '../components/clutter/control';
import Colophon from '../components/colophon';
import styles from '../assets/scss/layout.module.scss'
import utils from '../assets/scss/utils.module.scss' 
import Navigation from '../components/navigation';

export const siteTitle = "blikkjournal";
export const siteDescription = "a collection of moments and everyday observations";

export const viewport = {
  colorScheme: 'light',
}

const ronzino = localFont({
  src: [
    {
      path: '../assets/fonts/Ronzino-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Ronzino-Oblique.woff2',
      weight: '400',
      style: 'italic',
    }
  ]
})

export default function RootLayout({ children }) {
  
  return (
    <html lang="en" className={ronzino.className}>
    <body className={styles.wrapper}>    
    <ClutterProvider>
    <header className={styles.header}>
    <h1 className={utils.screen_reader_text}><Link href="/">{siteTitle}</Link></h1>
    <p className={styles.description}><em>blikkjournal</em> is a collection of moments and everyday observations.</p>
    <Navigation />
    <ClutterControl />
    </header>
    
    <main className={styles.content}>
    {children}
    </main>
    
    <footer className={styles.footer}>
    <p className={styles.credits}>© <a href="https://astridmathilde.no" rel="external" target="_blank">Astrid Boberg</a> 2018–{(new Date().getFullYear())}</p>
    
    <Colophon button="Colophon">
    <h2>Colophon</h2>
    <p>The typeface is <a href="https://www.collletttivo.it/typefaces/ronzino" target="_blank" rel="external">Ronzino</a> from <a href="https://www.collletttivo.it" target="_blank" rel="external">Collletttivo</a>. The icons are from <a href="https://ikonate.com" target="_blank" rel="external">Iconate</a>.</p>
    
    <p>Estimated carbon emissions for every page load is currently <a href="https://www.websitecarbon.com/website/blikk-directory/" rel="external" target="_blank" aria-label="Read source">0,03g of CO2</a> (last updated 25.03.26).</p>
    
    <p>The photos are stored in <a href="https://notion.com" target="_blank" rel="external">Notion</a> and retrieved using <a href="https://developers.notion.com" target="_blank" rel="external">Notion API</a>.</p>
    
    <p>The site is designed and coded by hand (not generated by AI) using <a href="https://www.figma.com"  target="_blank" rel="external">Figma</a> and <a href="https://nextjs.org" target="_blank" rel="external">Next.js</a>.</p>
    
    <p>Generative AI has been used for researching functionality and solving wicked problems. In most cases, the language model <a href="https://huggingface.co/google/gemma-3-12b-it" rel="external" target="_blank">Gemini 3 12b</a> has been used, running locally using <a href="https://osaurus.ai" rel="external" target="_blank">Osaurus</a>, reducing carbon emissions. In some cases where a local model was not sufficient, <a href="https://claude.ai" rel="external" target="_blank">Claude</a> has been used, as specified in <a href="https://github.com/astridmathilde/blikkjournal/tree/master/app" target="_blank" rel="external">the code</a>.</p>
    
    <p>If you are curious about how everything is built and where generative AI is used, the  <a href="https://github.com/astridmathilde/blikkjournal" target="_blank" rel="external">code repository</a> is open and public on <a href="https://github.com/astridmathilde/blikkjournal" target="_blank" rel="external">Github</a>.</p>
    
    <p>design and photos © <a href="https://astridmathilde.no" target="_blank" rel="external">Astrid Boberg</a> 2018–{(new Date().getFullYear())}</p>
    </Colophon>
    
    </footer>
    </ClutterProvider>
    </body>
    </html>
  );
}